# Generated by Django 4.2.1 on 2023-05-15 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TimeField(auto_now_add=True, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('distance', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Расстояние')),
            ],
        ),
    ]
