# Generated by Django 3.2.19 on 2023-05-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_table', '0003_auto_20230519_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
    ]
