# Generated by Django 4.2.1 on 2023-05-18 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_table', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=150, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.CharField(max_length=300, verbose_name='Название вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1500), django.core.validators.MinValueValidator(0)], verbose_name='Количество баллов за вопрос'),
        ),
    ]
