# Generated by Django 3.2.19 on 2023-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_table', '0004_remove_customuser_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
