# Generated by Django 3.2.19 on 2023-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_table', '0007_auto_20230521_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='file_mp3',
            field=models.FileField(blank=True, null=True, upload_to='musics'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='file_wav',
            field=models.FileField(blank=True, null=True, upload_to='musics'),
        ),
    ]
