# Generated by Django 4.2.1 on 2023-05-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Values_table',
        ),
    ]
